### ISSUE TITLE
LastKnownSwitchName

### ISSUE THREAD

**Issue by micalkin** [ejsiron/Posher-V#1]
The property 'LastKnownSwitchName' cannot be found on this object. Verify that the property exists.
At line:410 char:9
+                                 $VMSwitchName = $EthPortSettings.LastKnownSwitchName
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

**Comment by ejsiron** [comment]
What’s your Hyper-V/Management OS version? PowerShell version where you’re running the script?

**Comment by micalkin** [comment]
`Name                           Value                                                                                                                                                             
----                           -----                                                                                                                                                             
PSVersion                      4.0                                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                               
SerializationVersion           1.1.0.1                                                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                                                   
BuildVersion                   6.3.9600.19170                                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                                                              
PSRemotingProtocolVersion      2.2 `

This is in a Windows 2012 R2 environment.  Fully Patched.

**Comment by ejsiron** [comment]
Fixed in 1.2
